name: bmcs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - bokeh
  - numpy
  - scipy
  - sympy
  # - mayavi # conflict with python 3.7
  - traitsui
  - traits
  - yapf
  - pandas
  - seaborn
  - scikit-learn
  - matplotlib
  - cython
  - pip
  - pip: # https://github.com/conda/conda/pull/3969
      - --extra-index-url anaconda.org/rosoba bmcs
